project:
  type: website
  output-dir: docs

website:
  title: "Gustavo Marchant Allende"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: CV.qmd
        text: CV
      - href: Images.qmd
        text: Images

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

