project:
  type: website
  output-dir: docs

website:
  title: "Gustavo A. Marchant Allende"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: CV.qmd
        text: CV
      - href: gradapp.qmd
        text: Grad school apps

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

