project:
  type: website
  output-dir: docs

website:
  title: "Gustavo Marchant Allende"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: CV.qmd
        text: CV

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

