---
title: "CV"
about:
  template: solana
---

## Education

-   **Macalester College** \| St. Paul, MN <br> B.A. in Geology, minor in Data Science \| Sept 2021 - May 2025 <br> GPA: 3.88

Coursework (Spring 2024): Petrology & Geochemistry, Remote Sensing of the Environment, Geomorphology, Statistical Machine Learning, Linear Algebra, Mineralogy, Structural Geology, Introduction to GIS.

## Experience
-   **Macalester College** \| St. Paul, MN 
    <br> Geology Laboratory Assistant \| September 2022 - Present
    <br> - Operated petrographic and imaging laboratory equipment (Scanning Electron Microscope (SEI & EDS), X-Ray Diffractometer, Micro X-Ray Spectrometer) for students’ research and department inventory.
    <br> - Cataloged 500+ teaching and display mineralogical samples for the Geology department.
    <br> - Produced a new instruction manual with pictures and demonstrations for better SEM/EDS use and training.

-   **Macalester College** \| St. Paul, MN 
    <br> Undergraduate Teaching Assistant \| September 2023 - Present
    <br> - Introduction to Data Science (Fall 2023, Spring 2024).
    <br> - Empirical Research Methods (Fall 2023).
    
-   **Macalester College** \| St. Paul, MN 
    <br> Undergraduate Researcher \| June 2023 - September 2023
    <br> - Explored six thin sections of lunar volcanic ejecta collected by Apollo 17 astronauts to understand its geological history.
    <br> - Worked with Professor First to explore previous literature on lunar geology, experimental petrology, and olivine crystallization.
    <br> - Collected, organized, and classified data (SEM/EDS, PPL imaging) to qualitatively and quantitatively describe the mineralogy of these samples.
    <br> - Presented findings at the 2023 Macalester's Summer Research Poster Session and the 2023 National Diversity in STEM Conference.
    
-   **UWC Robert Bosch College** \| Freiburg, BW, Germany
    <br> Science Tutor \| September 2020 - May 2021
    <br> - Summarized course content for Biology and Earth Systems and Society to improve students’ retention and experiential learning of a variety of science concepts. 
    <br> - Recreated classroom activities and review sessions through engaging and clear communication with students and teachers.

## Leadership & Civic Engagement

-   **Society for the Advancement of Chicanos/Hispanics and Native Americans in STEM** \| Macalester College \| October 2023 - Present
    <br> - Established of the first SACNAS chapter at Macalester College, fostering an inclusive space for underrepresented students of color in science.
    <br> - Organized diverse events, including professional development sessions, graduate student talks, and informal gatherings, promoting engagement between students and professors.
    <br> - Lead the internal selection and preparation of students for the 2024 National Diversity in STEM conference, brainstorming how to deliver impactful poster presentations.
    
-   **GeoClub** \| Macalester College \| January 2024 - Present
    <br> - Co-chaired Macalester's club for geologists, promoting the geosciences within the community.
    <br> - Organized diverse events and collaborated with scientific institutions, like the Minnesota Science Museum, to make geology more accessible to a broader audience, particularly children.
    <br> - Lead a *Unlearning Racism in Geoscience* (URGE) initiative, fostering open dialogues among students and faculty, creating a platform to discuss and establish actionable steps to enhance diversity within the field.

-   **Adelante** \| Macalester College \| January 2022 - December 2023
    <br> - Co-chaired Macalester's oldest Latin American organization, fostering a unique space for Latinx students to share their experiences and grow as a community.
    <br> - Organized diverse events, including reflection sessions, archival research on Latinx history at our institution, and social events.

-   **ARCPIN Museum of Education** \| Instituto Nacional José Miguel Carrera \| May 2023 - August 2023
    <br> - Explored unclassified mineralogical and petrological collections to organize the museum’s scientific records and select samples for educational use.
    <br> - Developed classification diagrams and instructed high-school students on basic rock and mineral identification.
    <br> - Prepared mineral, rock, and fossil samples for display in a public gallery.

## Skills

-   Languages: Spanish, English (native, bilingual proficiency); German (advanced proficiency)

-   Software: R/Rstudio (advanced proficiency); Python (beginner proficiency); ArcGIS Pro, ArcGIS Online, QGIS (intermediate proficiency); Linux (beginner proficiency).

-   Laboratory: Scanning Electron Microscope (SEM/EDS); X-Ray Diffractometer; Micro X-Ray Spectrometer

## Awards and Certificates

-   Dean's List for Academic Excellence (all elegible semesters) \| Macalester College

-   Davis United World Colleges Scholar \| Davis UWC Foundation

-   United World College Scholar \| UWC Robert Bosch College

-   Wilderness/Remote First Aid Certificate \| National Outdoors Leadership School (NOLS)

-   German B1 Certificate \| Goethe Institut
